---
abstract: 'Base class and script for CPAN searching.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-CPAN-Search
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  CPAN: 0
  Class::Utils: 0.03
  Getopt::Std: 0
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-CPAN-Search
  homepage: https://github.com/tupinek/App-CPAN-Search
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/App-CPAN-Search
version: '0.04'
